set_property SRC_FILE_INFO {cfile:{c:/Users/Tugdual LE PELLETER/Documents/Recherche/Repositories/ip_afifo_axis/sources/ip/ip_afifo_axis/ip_afifo_axis/ip_afifo_axis_in_context.xdc} rfile:../../../../../sources/ip/ip_afifo_axis/ip_afifo_axis/ip_afifo_axis_in_context.xdc id:1 order:EARLY scoped_inst:inst_ip_afifo_axis} [current_design]
set_property src_info {type:SCOPED_XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_pins inst_ip_afifo_axis/m_aclk]
set_property src_info {type:SCOPED_XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_pins inst_ip_afifo_axis/s_aclk]
set_property src_info {type:SCOPED_XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells inst_ip_afifo_axis]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells inst_ip_afifo_axis]
